### ISSUE TITLE
Unparseable Date Exception

### ISSUE THREAD

**Issue by jesusalatorre** [hdsalazar9/LosLinces-DesarrolloParaMoviles#27]
Tratar agendar una medicina para tomarse en Mayo 23 resultó en:

05-05 15:02:22.611 5601-5601/itesm.mx.saludintegral W/System.err: java.text.ParseException: Unparseable date: "Tue Jan 23 00:00:00 CST 2018" (at offset 0)
05-05 15:02:22.611 5601-5601/itesm.mx.saludintegral W/System.err:     at java.text.DateFormat.parse(DateFormat.java:571)
05-05 15:02:22.611 5601-5601/itesm.mx.saludintegral W/System.err:     at itesm.mx.saludintegral.controllers.MedicamentoOperations.getAllProducts(MedicamentoOperations.java:119)
05-05 15:02:22.611 5601-5601/itesm.mx.saludintegral W/System.err:     at itesm.mx.saludintegral.fragments.FragmentoMedicamento.mostrarMedicamentos(FragmentoMedicamento.java:78)
05-05 15:02:22.612 5601-5601/itesm.mx.saludintegral W/System.err:     at itesm.mx.saludintegral.fragments.FragmentoMedicamento.onCreateView(FragmentoMedicamento.java:53)

**Comment by jesusalatorre** [comment]
Fixed
